= LiDAR-SLAM-RES
LiDAR SLAM Group <huiwu.luo@aliyun.com>
v0.1, 2019-03-26
:toc:
:icons: font

[.lead]
A page of `LiDAR SLAM Resources` (LiDAR-SLAM-RES) to follow up current SLAM trends and papers.

'''

== Papers
. [big red yellow-background]*_Google Cartographer_* +
Hess W, Kohler D, Rapp H, et al. Real-time loop closure in 2D LIDAR SLAM [C]//_2016 IEEE International Conference on Robotics and Automation (ICRA)_. IEEE, 2016: 1271-1278.

** https://ai.google/research/pubs/pub45466.pdf[**paper**],  https://blog.csdn.net/luohuiwu/article/details/88890307[paper-in-Chinese]

** **document(online)**: https://google-cartographer.readthedocs.io/en/latest/index.html[**cartographer-online**], 
https://google-cartographer-ros.readthedocs.io/en/latest/index.html[**cartographer-ros-online**]

** **document(pdf)**: 
https://media.readthedocs.org/pdf/google-cartographer/latest/google-cartographer.pdf[**cartographer(pdf)**], 
https://media.readthedocs.org/pdf/google-cartographer-ros/latest/google-cartographer-ros.pdf[**cartographer-ros(pdf)**]

** **code**: https://github.com/googlecartographer/cartographer[**cartographer**], https://google-cartographer-ros.readthedocs.io/en/latest/index.html[**cartographer-ros**]


** **data**:
https://google-cartographer-ros.readthedocs.io/en/latest/demos.html[ROS-demo-bag-files]

. [red]#*_Sparse Pose Adjustment_*# +
Konolige K, Grisetti G, Kümmerle R, et al. Efficient sparse pose adjustment for 2D mapping[C]//_2010 IEEE/RSJ International Conference on Intelligent Robots and Systems_. IEEE, 2010: 22-29.

** http://ais.informatik.uni-freiburg.de/publications/papers/konolige10iros.pdf[**paper**]

. *_Scan Matching_* +
Olson E B. Real-time correlative scan matching[C]//_2009 IEEE International Conference on Robotics and Automation_. IEEE, 2009: 4387-4393.

** https://april.eecs.umich.edu/media/pdfs/olson2009icra.pdf[**paper**]

. *_Branch and Bound Algorithm_* +
Clausen J. Branch and bound algorithms-principles and examples[J]. _Department of Computer Science, University of Copenhagen_, 1999: 1-30.

** http://janders.eecg.toronto.edu/1387/readings/b_and_b.pdf[paper]


== Notes
(to be continued)

== Reference
Repository was inspired by:

* https://github.com/Ewenwan/MVision[MVision Machine Vision]

* https://github.com/tzutalin/awesome-visual-slam[awesome-visual-slam]