= LiDAR-SLAM-RES
LiDAR SLAM Group <huiwu.luo@aliyun.com>
v0.1, 2019-03-26
:toc:
:icons: font

[.lead]
A page of `LiDAR SLAM Navigatio Resources` (LiDAR-SLAM-Nav-RES) to follow up current LiDAR SLAM based Navigation trends, including key papers, books, engineering projects, as well as valuable blogs.

'''

== (Current) Project III -- Motion Planning

=== ROS Research Papers

* [red]#*_ROS Layered Costmaps_*#

> David V. Lu, D. Hershberger and W. D. Smart, "*_Layered costmaps for context-sensitive navigation_*," 2014 IEEE/RSJ International Conference on Intelligent Robots and Systems, Chicago, IL, 2014, pp. 709-715. http://wustl.probablydavid.com/publications/IROS2014.pdf[pdf]
>
> * [red]#(2019/07/05)# https://github.com/teddyluo/ROSCostmap-Chinese[中文翻译：《上下文敏感的导航分层代价地图》] 
> * https://zhuanlan.zhihu.com/p/28162685[ROS costmap_2D理解]
> * https://pan.baidu.com/s/182GHhXS_QQwN_y48k2J1Pg[Video,百度网盘] (提取码`7ify`)
> * https://scholar.google.com/citations?user=bfksbjAAAAAJ&hl=zh-CN[David V. Lu's page in Google Scholar]
> * David Vincent Lu, "*_Contextualized Robot Navigation_*" (2014). Engineering and Applied Science Theses & Dissertations. 62. https://openscholarship.wustl.edu/cgi/viewcontent.cgi?article=1062&context=eng_etds[pdf], https://www.mobt3ath.com/uplode/book/book-2423.pdf[pdf(candidate)]

* [red]#*_Layered Social Cost Map_*#

> * Kollmitz, Marina, et al. "*_Time Dependent Planning on a Layered Social Cost Map for Human-Aware Robot Navigation_*." 2015 European Conference on Mobile Robots (ECMR). IEEE, 2015.  http://ais.informatik.uni-freiburg.de/publications/papers/kollmitz15ecmr.pdf[pdf]
> * [red]#*_(2019/07/19)_*# David V. Lu, Daniel B. Allan, and William D. Smart. "*_Tuning Cost Functions for Social Navigation_*." International Conference on Social Robotics. Springer, Cham, 2013. https://pdfs.semanticscholar.org/73e3/ccd7a03eb1d8d4a9354e5c44d314f7f1199f.pdf[pdf]

* [red]#*_ROS Navigation Tuning Guide_*#

> Kaiyu Zheng, https://github.com/zkytony/ROSNavigationGuide/blob/master/main.pdf[*_ROS Navigation Tuning Guide_*]. arXiv preprint arXiv:1706.09068v2, Sep. 2016. https://github.com/zkytony/ROSNavigationGuide/blob/master/main.pdf[pdf]
>
> * 中文翻译： https://github.com/teddyluo/ROSNavGuide-Chinese[《ROS导航功能调优指南》]
>
> * ROS Wiki: http://wiki.ros.org/navigation/Tutorials/Navigation%20Tuning%20Guide[link]

* [red]#*_ROS Navigation: Concepts and Tutorial_*#

> Guimarães R L, de Oliveira A S, Fabro J A, et al. *_ROS navigation: Concepts and tutorial[M]_*//Robot Operating System (ROS). Springer, Cham, 2016: 121-160. https://www.researchgate.net/profile/Joao_Fabro/publication/302986850_ROS_Navigation_Concepts_and_Tutorial/links/5b0c2f51aca2725783ec37c4/ROS-Navigation-Concepts-and-Tutorial.pdf[pdf]

* [red]#*_Robotics Engineering 2: ROS-Turtlebot Motion Control and Navigation_*#

> AK Assad, Mashruf Chowdhury, and Yanik Porto, *_Robotics Engineering 2: ROS-Turtlebot Motion Control and Navigation_*. May 11, 2015. http://mangoprojects.info/wp-content/uploads/2015/06/ros_report.pdf[pdf]


=== Books


> * Robotics (Release 1.4)
>
> > Jeff McGough, Book title: *_Robotics_*. Date: Dec./02/2018. http://roboscience.org/book/Robotics.pdf[*pdf*]
> 
> * 《机器人操作系统（ROS）史话36 篇》
>
> > 张新宇, http://www.roseducation.org/docs/ROS_history.pdf[pdf]
> 
> * 《人类找北史：从罗盘到GPS，导航定位的过去与未来》
>
> > Bray, Hiawatha. You are here: From the compass to GPS, the history and future of how we find ourselves. Basic Books (AZ), 2014. link:./pdfs/2018-You-are-here.pdf[pdf（中文翻译）]

//// 
. [red]#*_Sparse Pose Adjustment (SPA)_*# +
Konolige K, Grisetti G, Kümmerle R, et al. Efficient sparse pose adjustment for 2D mapping[C]//_2010 IEEE/RSJ International Conference on Intelligent Robots and Systems_. IEEE, 2010: 22-29.
////

=== Courses
____
* 《智能机器人系统》

> 国防科技大学智能科学学院, 卢惠民，郑志强，韦庆，肖军浩，杨绍武，曾志文， http://www.icourse163.org/course/NUDT-1205969803[link]

* 《机器人操作系统入门》(2018)

> 中科院软件所&中科重德机器人公司, 柴长坤, https://www.icourse163.org/course/0802ISCAS001-1002580008[link]
____

=== Online Resources

=== Tutorials

____
* 机器人操作系统（ROS）暑期学校, type: video&pdf, http://www.roseducation.org/[link]
//. ROS激光SLAM导航理解, type: blog, https://blog.csdn.net/luohuiwu/article/details/92787237[link]
* [red]#专栏文章#：ROS激光SLAM导航(`move_base`参数配置注释), type: blog, https://blog.csdn.net/luohuiwu/column/info/40494[link]

* 小强ROS机器人教程, type: pdf,  http://community.bwbot.org/topic/110/%E5%B0%8F%E5%BC%BA%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C%E5%92%8C%E6%95%99%E7%A8%8B%E7%9B%AE%E5%BD%95[link]

* 机器人操作系统（ROS）浅析, type:pdf,  https://www.cse.sc.edu/~jokane/agitr/%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%EF%BC%88ROS%EF%BC%89%E6%B5%85%E6%9E%90.pdf[link]
* ROS小课堂, type:blog, https://www.corvin.cn/posts[link]
____

==== Notes
____
* http://wiki.ros.org/cn/navigation[ROS Nav Wiki]
* https://zhuanlan.zhihu.com/ros-nav[ROS Navigation Stack源码学习]
* https://www.ncnynl.com/category/ros-navigation/[ROS与navigation教程 by 创客智造]
* link:./notes/Turtle2eNavParamExp.md[*Turtlebot 2e 导航之move_base参数详解*]
____
 
=== Projects

____
. [red]#*_PythonRobotics_*# +
** https://github.com/AtsushiSakai/PythonRobotics[github (!!Excellent!!)]
. ROS Navigation Stack +
** https://github.com/ros-planning/navigation[github]
____

=== 机器人硬件

==== 1) 硬件平台
____
* EAI机器人， http://www.eaibot.cn/cn/download[资料]
* 小强机器人， http://www.bwbot.org/zh-cn/[蓝鲸智能机器人]
* 思岚科技（SLAMTEC）: http://www.slamtec.com/[link]
* miiboo机器人： https://www.cnblogs.com/hiram-zhang/[link]
____

==== 2) AGV 国家标准

____
* 《GB/T 30029 自动导引车（AGV） 设计通则》, http://www.std.gov.cn/gb/search/gbDetailed?id=71F772D7EC55D3A7E05397BE0A0AB82A[pdf], http://www.agvchina.com/index.aspx?lanmuid=93&sublanmuid=763&id=5[pdf(candidate )]

* 《GB/T 30030 自动导引车（AGV） 术语》, http://www.std.gov.cn/gb/search/gbDetailed?id=71F772D7EC56D3A7E05397BE0A0AB82A[pdf],  http://www.agvchina.com/index.aspx?lanmuid=93&sublanmuid=763&id=6[pdf(candidate )]

* 《GB/T 20721 自动导引车 通用技术条件》, http://www.std.gov.cn/gb/search/gbDetailed?id=71F772D7F46CD3A7E05397BE0A0AB82A[pdf]
____

== Project I -- Hardware Configuration: Laser and IMU Sensors

. Laser: Osight LSXXX^TM^ laser sensor configuration & test: +
link:./notes/ROS_Osight_LSXXX.adoc[*configuration*]

. IMU: 
** https://github.com/KristofRobot/razor_imu_9dof[Sparkfun 9DoF Razor IMU (MPU-9250)]
** https://github.com/teddyluo/hipnuc_imu_ros[HiPNUC HI216]

== Project II -- Laser-based SLAM (Part 1): Google Cartographer
. [big red yellow-background]*_Google Cartographer_* +
Hess W, Kohler D, Rapp H, et al. Real-time loop closure in 2D LIDAR SLAM [C]//_2016 IEEE International Conference on Robotics and Automation (ICRA)_. IEEE, 2016: 1271-1278.

** https://ai.google/research/pubs/pub45466.pdf[**paper**],  https://blog.csdn.net/luohuiwu/article/details/88890307[中文翻译]

** **document(online)**: https://google-cartographer.readthedocs.io/en/latest/[Cartographer], 
https://google-cartographer-ros.readthedocs.io/en/latest/[Cartographer ROS], 
https://google-cartographer-ros-for-turtlebots.readthedocs.io/en/latest/[Cartographer ROS for TurtleBots]

** **document(pdf)**: 
https://readthedocs.org/projects/google-cartographer/downloads/pdf/latest/[Cartographer], 
https://readthedocs.org/projects/google-cartographer-ros/downloads/pdf/latest/[Cartographer ROS], 
https://readthedocs.org/projects/google-cartographer-ros-for-turtlebots/downloads/pdf/latest/[Cartographer ROS for TurtleBots]

** **code**: https://github.com/googlecartographer/cartographer[Cartographer], https://github.com/googlecartographer/cartographer_ros[Cartographer ROS], 
https://github.com/googlecartographer/cartographer_turtlebot[Cartographer ROS for TurtleBots]

** **data**:
https://google-cartographer-ros.readthedocs.io/en/latest/demos.html[ROS-demo-bag-files], 
https://pan.baidu.com/s/1zfeaY9r1OudkaJ2Y7y-iCQ[**百度网盘下载**] (提取码: j47t)

** **source(compressed)**: 
https://gitee.com/teddyluo/Google-Cartographer-Packages[Google-Cartographer-Packages]


//// 
*** Deutsches Museum: + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_2d/cartographer_paper_deutsches_museum.bag[**2D backpack demo file, 470.52MB**], + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_3d/with_intensities/b3-2016-04-05-14-14-00.bag[**3D backpack demo file, 9.11GB**], + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_2d/b2-2016-04-05-14-44-52.bag[**b2-2016-04-05-14-44-52.bag, 89.63MB**], + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_2d/b2-2016-04-27-12-31-41.bag[**b2-2016-04-27-12-31-41.bag, 222.36MB**], + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_3d/b3-2016-04-05-13-54-42.bag[**b3-2016-04-05-13-54-42.bag, 5.70GB**], + 
https://storage.googleapis.com/cartographer-public-data/bags/backpack_3d/b3-2016-04-05-15-52-20.bag[**b3-2016-04-05-15-52-20.bag, 2.53GB**]

*** Static landmarks: 
https://storage.googleapis.com/cartographer-public-data/bags/mir/landmarks_demo_uncalibrated.bag[**landmarks_demo_uncalibrated.bag, 41.71MB**]

*** Revo LDS: 
https://storage.googleapis.com/cartographer-public-data/bags/revo_lds/cartographer_paper_revo_lds.bag[**cartographer_paper_revo_lds.bag, 3.30MB**]

*** PR2: 
https://storage.googleapis.com/cartographer-public-data/bags/pr2/2011-09-15-08-32-46.bag[**2011-09-15-08-32-46.bag, 3.66GB**]

*** Taurob Tracker:
https://storage.googleapis.com/cartographer-public-data/bags/taurob_tracker/taurob_tracker_simulation.bag[**taurob_tracker_simulation.bag, 42.35MB**]
////


.. [red]#*_Sparse Pose Adjustment (SPA)_*# +
Konolige K, Grisetti G, Kümmerle R, et al. Efficient sparse pose adjustment for 2D mapping[C]//_2010 IEEE/RSJ International Conference on Intelligent Robots and Systems_. IEEE, 2010: 22-29.

** http://ais.informatik.uni-freiburg.de/publications/papers/konolige10iros.pdf[**paper**]

.. *_Correlative Scan Matching_* +
  Olson E B. Real-time correlative scan matching[C]//_2009 IEEE International Conference on Robotics and Automation_. IEEE, 2009: 4387-4393.
  ** https://april.eecs.umich.edu/media/pdfs/olson2009icra.pdf[**paper**]

.. [red]#*_Ceres Scan Matching_*# + 
  Kohlbrecher S, Von Stryk O, Meyer J, et al. A flexible and scalable slam system with full 3d motion estimation[C]//_2011 IEEE International Symposium on Safety, Security, and Rescue Robotics_. IEEE, 2011: 155-160.
  ** http://www.gkmm.informatik.tu-darmstadt.de/publications/files/slam2011.pdf[**paper**]

.. [red]#*_Branch and Bound Algorithm_*# +
Clausen J. Branch and bound algorithms-principles and examples[J]. _Department of Computer Science, University of Copenhagen_, 1999: 1-30.

** http://janders.eecg.toronto.edu/1387/readings/b_and_b.pdf[paper]

== Project II -- Laser-based SLAM (Part 2):  LiDAR SLAM Survey
. Castellanos, J.A., Neira, J., & Tardós, J.D. (2005). http://webdiis.unizar.es/GRPTR/pubs/Caste_AMR_2006.pdf[*_Map Building and SLAM Algorithms_*].
. Santos, J. M., Portugal, D., & Rocha, R. P. (2013, October). http://eprints.lincoln.ac.uk/14672/1/06719348.pdf[*_An evaluation of 2D SLAM techniques available in robot operating system_*]. In 2013 IEEE International Symposium on Safety, Security, and Rescue Robotics (SSRR) (pp. 1-6). IEEE.
. Mendes, E., Koch, P., & Lacroix, S. (2016, October). https://core.ac.uk/download/pdf/29175747.pdf[*_ICP-based pose-graph SLAM_*]. In 2016 IEEE International Symposium on Safety, Security, and Rescue Robotics (SSRR) (pp. 195-200). IEEE.
. Alexandersson, J., & Nordin, O. (2017). https://liu.diva-portal.org/smash/get/diva2:1218791/FULLTEXT01.pdf[*_Implementation of SLAM algorithms in a small-scale vehicle using model-based development_*].
. Yagfarov, Rauf & Ivanou, Mikhail & Afanasyev, Ilya. (2018). https://www.researchgate.net/publication/330168394_Map_Comparison_of_Lidar-based_2D_SLAM_Algorithms_Using_Precise_Ground_Truth[*_Map Comparison of Lidar-based 2D SLAM Algorithms Using Precise Ground Truth_*]. 10.1109/ICARCV.2018.8581131. 
. Felipe Jiménez, Miguel Clavijo and Javier Juana. (VEHICULAR 2018). https://www.thinkmind.org/download.php?articleid=vehicular_2018_4_20_30043[*_LiDAR-based SLAM algorithm for indoor scenarios_*]. 
. Yagfarov, R., Ivanou, M., & Afanasyev, I. (2018, November).  https://www.researchgate.net/publication/328007381_Comparison_of_Various_SLAM_Systems_for_Mobile_Robot_in_an_Indoor_Environment[*_Map Comparison of Lidar-based 2D SLAM Algorithms Using Precise Ground Truth_*]. In 2018 15th International Conference on Control, Automation, Robotics and Vision (ICARCV) (pp. 1979-1983). IEEE.
. Kümmerle, R., Steder, B., Dornhege, C., Ruhnke, M., Grisetti, G., Stachniss, C., & Kleiner, A. (2009). http://www2.informatik.uni-freiburg.de/~stachnis/pdf/kuemmerle09auro.pdf[*_On measuring the accuracy of SLAM algorithms_*]. Autonomous Robots, 27(4), 387.
. Chen, Y., Tang, J., Jiang, C., Zhu, L., Lehtomäki, M., Kaartinen, H., ... & Zhou, H. (2018). https://www.mdpi.com/1424-8220/18/10/3228/pdf[*_The accuracy comparison of three simultaneous localization and mapping (SLAM)-Based indoor mapping technologies_*]. Sensors, 18(10), 3228.





////
== Reference
Repository was inspired by https://github.com/Ewenwan/MVision[MVision Machine Vision]
* https://github.com/tzutalin/awesome-visual-slam[awesome-visual-slam]
////
